#!/bin/bash

set -e # stop on error
set -x # echo commands

on_error() {
  echo "build failed"
}
trap "on_error" ERR

on_done() {
  exit ${@:2}
}
trap "on_done" EXIT

name="autosr"
go mod tidy

go test ./...
GOOS=darwin go build -o dist/osx/$name-osx
GOOS=darwin GOARCH=arm64 go build -o dist/osx/$name-osx-arm64
GOOS=linux go build -o dist/linux/$name
GOOS=windows go build -o dist/windows/${name}.exe

go install
